[global]
daemonize = no
error_log = /tmp/no-alone-fpm-error.log

[no-alone]
user = yar101
group = yar101
listen = /tmp/no-alone-fpm.sock
listen.owner = yar101
listen.group = yar101
listen.mode = 0660
pm = dynamic
pm.max_children = 10
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 5
