<?php

namespace App\Http\Controllers;

use App\Models\ContentPack;
use App\Models\ContentPackPhoto;
use App\Models\ContentPackPurchase;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\URL;
use Inertia\Inertia;
use Inertia\Response;

class GalleryController extends Controller
{
    public function index(): Response
    {
        $userId = auth()->id();
        $user   = auth()->user();

        // Distinct idols from whom the user purchased content, ordered by most recent purchase
        $idols = \Illuminate\Support\Facades\DB::table('content_pack_purchases')
            ->join('content_packs', 'content_pack_purchases.content_pack_id', '=', 'content_packs.id')
            ->join('users', 'content_packs.user_id', '=', 'users.id')
            ->where('content_pack_purchases.user_id', $userId)
            ->whereNull('users.deleted_at')
            ->select(
                'users.id',
                'users.name',
                'users.avatar_path',
                'users.active_frame_id'
            )
            ->selectRaw('MAX(CASE WHEN content_pack_purchases.viewed_at IS NULL THEN 1 ELSE 0 END) as has_new_packs')
            ->selectRaw('MAX(content_pack_purchases.purchased_at) as last_purchased_at')
            ->groupBy('users.id', 'users.name', 'users.avatar_path', 'users.active_frame_id')
            ->orderByDesc('last_purchased_at')
            ->get()
            ->map(function ($row) {
                // To attach the avatar URL properly, we can instantiate a dummy model or just use the accessor logic
                // But since active_frame_id is there, it's easier to hydrate a User model
                $user = new \App\Models\User();
                $user->id = $row->id;
                $user->name = $row->name;
                $user->avatar_path = $row->avatar_path;
                $user->active_frame_id = $row->active_frame_id;
                // If we need the active frame relationship, we might need to load it
                // To avoid N+1 here for active frames, let's just let it lazy load if requested,
                // or we can eager load them. For now, avatar_url is generated by the accessor.
                
                return [
                    'id'            => $user->id,
                    'name'          => $user->name,
                    'avatar_url'    => $user->avatar_url,
                    'has_new_packs' => (bool) $row->has_new_packs,
                ];
            });

        $hasNewPacks = ContentPackPurchase::where('user_id', $userId)->whereNull('viewed_at')->exists();

        return Inertia::render('Gallery/Index', [
            'idols'         => $idols,
            'is_idol'       => (bool) $user->is_idol,
            'has_new_packs' => $hasNewPacks,
        ]);
    }

    public function photos(Request $request): JsonResponse
    {
        $userId  = auth()->id();
        $user    = auth()->user();
        $idolId  = $request->input('idol_id');
        $mine    = $request->boolean('mine');
        $cursor  = $request->input('cursor'); // last seen photo id
        $perPage = 24;

        $packId  = $request->input('pack_id');
        $isNew   = $request->boolean('is_new');

        // Idol viewing their own content pack photos
        if ($mine && $user->is_idol) {
            $query = ContentPackPhoto::query()
                ->join('content_packs', 'content_pack_photos.content_pack_id', '=', 'content_packs.id')
                ->where('content_packs.user_id', $userId)
                ->when($packId, fn ($q) => $q->where('content_pack_photos.content_pack_id', $packId))
                ->when($cursor, fn ($q) => $q->where('content_pack_photos.id', '<', $cursor))
                ->select(
                    'content_pack_photos.id',
                    'content_pack_photos.path',
                    'content_pack_photos.content_pack_id',
                    'content_packs.title as pack_title',
                    'content_packs.user_id as idol_id'
                )
                ->orderByDesc('content_pack_photos.id')
                ->limit($perPage + 1);

            $photos  = $query->get();
            $hasMore = $photos->count() > $perPage;
            if ($hasMore) {
                $photos = $photos->take($perPage);
            }
            $nextCursor = $hasMore ? $photos->last()?->id : null;

            return response()->json([
                'photos' => $photos->map(fn ($ph) => [
                    'id'         => $ph->id,
                    'url'        => $ph->url,
                    'pack_id'    => $ph->content_pack_id,
                    'pack_title' => $ph->pack_title,
                    'idol_id'    => $ph->idol_id,
                ])->values(),
                'next_cursor' => $nextCursor,
                'has_more'    => $hasMore,
            ]);
        }

        // Join through purchases -> content_packs -> content_pack_photos
        $query = ContentPackPhoto::query()
            ->join('content_packs', 'content_pack_photos.content_pack_id', '=', 'content_packs.id')
            ->join('content_pack_purchases', function ($join) use ($userId) {
                $join->on('content_pack_purchases.content_pack_id', '=', 'content_packs.id')
                     ->where('content_pack_purchases.user_id', '=', $userId);
            })
            ->where('content_packs.status', 'published')
            ->when($isNew, fn ($q) => $q->whereNull('content_pack_purchases.viewed_at'))
            ->when($idolId, fn ($q) => $q->where('content_packs.user_id', $idolId))
            ->when($packId, fn ($q) => $q->where('content_pack_photos.content_pack_id', $packId))
            ->when($cursor, fn ($q) => $q->where('content_pack_photos.id', '<', $cursor))
            ->select(
                'content_pack_photos.id',
                'content_pack_photos.path',
                'content_pack_photos.content_pack_id',
                'content_packs.title as pack_title',
                'content_packs.user_id as idol_id'
            )
            ->orderByDesc('content_pack_photos.id')
            ->limit($perPage + 1);

        $photos  = $query->get();
        $hasMore = $photos->count() > $perPage;
        if ($hasMore) {
            $photos = $photos->take($perPage);
        }

        $nextCursor = $hasMore ? $photos->last()?->id : null;

        return response()->json([
            'photos' => $photos->map(fn ($ph) => [
                'id'         => $ph->id,
                'url'        => $ph->url,
                'pack_id'    => $ph->content_pack_id,
                'pack_title' => $ph->pack_title,
                'idol_id'    => $ph->idol_id,
            ])->values(),
            'next_cursor' => $nextCursor,
            'has_more'    => $hasMore,
        ]);
    }

    public function packs(Request $request): JsonResponse
    {
        $userId  = auth()->id();
        $user    = auth()->user();
        $idolId  = $request->input('idol_id');
        $mine    = $request->boolean('mine');
        $isNew   = $request->boolean('is_new');
        $cursor  = $request->input('cursor');
        $perPage = 20;

        if ($mine && $user->is_idol) {
            $query = ContentPack::where('user_id', $userId)
                ->with('coverPhoto')
                ->withCount('photos')
                ->when($cursor, fn ($q) => $q->where('id', '<', $cursor))
                ->orderByDesc('id');
        } else {
            $query = ContentPack::withTrashed()
                ->whereHas('purchases', fn ($q) => $q->where('user_id', $userId)->when($isNew, fn ($q2) => $q2->whereNull('viewed_at')))
                ->with(['purchases' => fn ($q) => $q->where('user_id', $userId)])
                ->where('status', 'published')
                ->when($idolId, fn ($q) => $q->where('user_id', $idolId))
                ->with('coverPhoto')
                ->withCount('photos');

            if ($isNew) {
                // To sort by purchased_at correctly with pagination, we join purchases
                $query->join('content_pack_purchases', function ($join) use ($userId) {
                    $join->on('content_pack_purchases.content_pack_id', '=', 'content_packs.id')
                         ->where('content_pack_purchases.user_id', '=', $userId);
                })
                ->addSelect('content_packs.*', 'content_pack_purchases.purchased_at', 'content_pack_purchases.id as purchase_id')
                ->when($cursor, fn ($q) => $q->where('content_pack_purchases.id', '<', $cursor))
                ->orderByDesc('content_pack_purchases.id');
            } else {
                $query->when($cursor, fn ($q) => $q->where('id', '<', $cursor))
                      ->orderByDesc('id');
            }
        }

        $packs   = $query->limit($perPage + 1)->get();
        $hasMore = $packs->count() > $perPage;
        if ($hasMore) {
            $packs = $packs->take($perPage);
        }

        return response()->json([
            'packs'       => $packs->map(fn ($p) => [
                'id'          => $p->id,
                'title'       => $p->title,
                'photo_count' => $p->photos_count,
                'cover_url'   => $p->cover_url,
                'is_new'      => !$mine && $p->purchases && $p->purchases->first() && is_null($p->purchases->first()->viewed_at),
            ])->values(),
            'next_cursor' => $hasMore ? ($isNew && !$mine ? $packs->last()?->purchase_id : $packs->last()?->id) : null,
            'has_more'    => $hasMore,
        ]);
    }
}
