<?php

namespace App\Http\Controllers;

use App\Models\AdminBroadcast;
use App\Models\AdminBroadcastRead;
use Illuminate\Http\Request;

class NotificationController extends Controller
{
    // Notification types generated by the platform (go to "Сервис" tab)
    private const SERVICE_TYPES = ['idol_approved', 'idol_rejected'];

    public function index(Request $request)
    {
        $user = $request->user();

        $notifications = $user->notifications()
            ->latest()
            ->take(30)
            ->get()
            ->filter(fn($n) => !in_array($n->data['type'] ?? '', self::SERVICE_TYPES))
            ->values()
            ->map(fn($n) => [
                'id' => $n->id,
                'source' => 'notification',
                'type' => $n->data['type'] ?? 'info',
                'message' => $n->data['message'] ?? '',
                'reason' => $n->data['reason'] ?? null,
                'read_at' => $n->read_at?->toIso8601String(),
                'created_at' => $n->created_at->toIso8601String(),
            ]);

        $placeholders = implode(',', array_fill(0, count(self::SERVICE_TYPES), '?'));
        $unread = $user->unreadNotifications()
            ->whereRaw("(data::jsonb->>'type') NOT IN ($placeholders)", self::SERVICE_TYPES)
            ->count();

        return response()->json([
            'notifications' => $notifications,
            'unread_count' => $unread,
        ]);
    }

    public function service(Request $request)
    {
        $user = $request->user();
        $readIds = AdminBroadcastRead::where('user_id', $user->id)->pluck('broadcast_id')->toArray();

        // Service notifications (idol status, etc.)
        $placeholders = implode(',', array_fill(0, count(self::SERVICE_TYPES), '?'));
        $serviceNotifs = $user->notifications()
            ->whereRaw("(data::jsonb->>'type') IN ($placeholders)", self::SERVICE_TYPES)
            ->latest()
            ->take(30)
            ->get()
            ->map(fn($n) => [
                'id' => $n->id,
                'source' => 'notification',
                'title' => null,
                'message' => $n->data['message'] ?? '',
                'reason' => $n->data['reason'] ?? null,
                'read_at' => $n->read_at?->toIso8601String(),
                'created_at' => $n->created_at->toIso8601String(),
            ]);

        // Admin broadcasts
        $broadcasts = AdminBroadcast::forUser($user)->latest()->take(30)->get()
            ->map(fn($b) => [
                'id' => 'b_' . $b->id,
                'source' => 'broadcast',
                'broadcast_id' => $b->id,
                'title' => $b->title,
                'message' => $b->body,
                'reason' => null,
                'read_at' => in_array($b->id, $readIds) ? true : null,
                'created_at' => $b->created_at->toIso8601String(),
            ]);

        // Merge and sort by date desc
        $items = $serviceNotifs->concat($broadcasts)
            ->sortByDesc('created_at')
            ->values();

        $unreadNotifs = $user->unreadNotifications()
            ->whereRaw("(data::jsonb->>'type') IN ($placeholders)", self::SERVICE_TYPES)
            ->count();
        $unreadBroadcasts = AdminBroadcast::forUser($user)->whereNotIn('id', $readIds)->count();

        return response()->json([
            'items' => $items,
            'unread_count' => $unreadNotifs + $unreadBroadcasts,
        ]);
    }

    public function markRead(Request $request, string $id)
    {
        $notification = $request->user()->notifications()->findOrFail($id);
        $notification->markAsRead();

        return response()->json(['ok' => true]);
    }

    public function markAllRead(Request $request)
    {
        $user = $request->user();
        $placeholders = implode(',', array_fill(0, count(self::SERVICE_TYPES), '?'));
        $user->unreadNotifications()
            ->whereRaw("(data::jsonb->>'type') NOT IN ($placeholders)", self::SERVICE_TYPES)
            ->get()
            ->each->markAsRead();

        return response()->json(['ok' => true]);
    }

    public function markBroadcastRead(Request $request, int $id)
    {
        $user = $request->user();
        $broadcast = AdminBroadcast::forUser($user)->findOrFail($id);

        AdminBroadcastRead::firstOrCreate(
            ['broadcast_id' => $broadcast->id, 'user_id' => $user->id],
            ['read_at' => now()]
        );

        return response()->json(['ok' => true]);
    }

    public function markAllServiceRead(Request $request)
    {
        $user = $request->user();

        // Mark service notifications as read
        $placeholders = implode(',', array_fill(0, count(self::SERVICE_TYPES), '?'));
        $user->unreadNotifications()
            ->whereRaw("(data::jsonb->>'type') IN ($placeholders)", self::SERVICE_TYPES)
            ->get()
            ->each->markAsRead();

        // Mark all broadcasts as read
        $readIds = AdminBroadcastRead::where('user_id', $user->id)->pluck('broadcast_id')->toArray();
        AdminBroadcast::forUser($user)->whereNotIn('id', $readIds)->get()
            ->each(fn($b) => AdminBroadcastRead::create([
                'broadcast_id' => $b->id,
                'user_id' => $user->id,
                'read_at' => now(),
            ]));

        return response()->json(['ok' => true]);
    }

    // Keep old messages methods for backwards compat (used by admin MessageController tests etc.)
    public function messages(Request $request)
    {
        return $this->service($request);
    }
}
