<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use Illuminate\Http\Request;

class NotificationController extends Controller
{
    // Notification types generated by the platform (go to "Сервис" tab)
    private const SERVICE_TYPES = ['idol_approved', 'idol_rejected', 'admin_broadcast', 'low_rating_warning', 'admin_rating', 'review_dispute_approved', 'review_dispute_rejected', 'content_pack_approved', 'content_pack_remarks', 'content_pack_rejected'];
    private const ORDER_TYPES   = ['order_created', 'order_accepted', 'order_cancelled', 'order_paid', 'order_completed'];

    private function window(Request $request): array
    {
        $before      = $request->input('before') ? Carbon::parse($request->input('before')) : null;
        $windowStart = ($before ?? now())->copy()->subHours(48);
        return [$before, $windowStart];
    }

    public function index(Request $request)
    {
        $user = $request->user();
        [$before, $windowStart] = $this->window($request);

        $excluded     = array_merge(self::SERVICE_TYPES, self::ORDER_TYPES);
        $placeholders = implode(',', array_fill(0, count($excluded), '?'));

        $query = $user->notifications()
            ->whereRaw("(data::jsonb->>'type') NOT IN ($placeholders)", $excluded);

        $items = (clone $query)
            ->where('created_at', '>=', $windowStart)
            ->when($before, fn($q) => $q->where('created_at', '<', $before))
            ->latest()
            ->get()
            ->map(fn($n) => [
                'id'         => $n->id,
                'source'     => 'notification',
                'type'       => $n->data['type'] ?? 'info',
                'message'    => $n->data['message'] ?? '',
                'reason'     => $n->data['reason'] ?? null,
                'read_at'    => $n->read_at?->toIso8601String(),
                'created_at' => $n->created_at->toIso8601String(),
            ])->values();

        $hasMore = (clone $query)->where('created_at', '<', $windowStart)->exists();

        $unread = $user->unreadNotifications()
            ->whereRaw("(data::jsonb->>'type') NOT IN ($placeholders)", $excluded)
            ->count();

        return response()->json([
            'notifications' => $items,
            'unread_count'  => $unread,
            'has_more'      => $hasMore,
        ]);
    }

    public function service(Request $request)
    {
        $user = $request->user();
        [$before, $windowStart] = $this->window($request);

        $placeholders = implode(',', array_fill(0, count(self::SERVICE_TYPES), '?'));

        $query = $user->notifications()
            ->whereRaw("(data::jsonb->>'type') IN ($placeholders)", self::SERVICE_TYPES);

        $items = (clone $query)
            ->where('created_at', '>=', $windowStart)
            ->when($before, fn($q) => $q->where('created_at', '<', $before))
            ->latest()
            ->get()
            ->map(fn($n) => [
                'id'         => $n->id,
                'source'     => 'notification',
                'type'       => $n->data['type'] ?? null,
                'title'      => $n->data['title'] ?? null,
                'message'    => $n->data['message'] ?? '',
                'reason'     => $n->data['reason'] ?? null,
                'read_at'    => $n->read_at?->toIso8601String(),
                'created_at' => $n->created_at->toIso8601String(),
            ])->values();

        $hasMore = (clone $query)->where('created_at', '<', $windowStart)->exists();

        $unreadCount = $user->unreadNotifications()
            ->whereRaw("(data::jsonb->>'type') IN ($placeholders)", self::SERVICE_TYPES)
            ->count();

        return response()->json([
            'items'        => $items,
            'unread_count' => $unreadCount,
            'has_more'     => $hasMore,
        ]);
    }

    public function combined(Request $request)
    {
        $user = $request->user();
        [$before, $windowStart] = $this->window($request);

        $query = $user->notifications()
            ->where('created_at', '>=', $windowStart)
            ->when($before, fn($q) => $q->where('created_at', '<', $before))
            ->latest();

        $items = $query->get()->map(function ($n) {
            $type = $n->data['type'] ?? 'info';
            $cat  = in_array($type, self::ORDER_TYPES) ? 'order' : 'service';

            $base = [
                'id'         => $n->id,
                'type'       => $type,
                '_cat'       => $cat,
                'read_at'    => $n->read_at?->toIso8601String(),
                'created_at' => $n->created_at->toIso8601String(),
            ];

            if ($cat === 'order') {
                return array_merge($base, [
                    'order_id' => $n->data['order_id'] ?? null,
                    'data'     => $n->data,
                ]);
            }

            return array_merge($base, [
                'source'  => 'notification',
                'title'   => $n->data['title'] ?? null,
                'message' => $n->data['message'] ?? '',
                'reason'  => $n->data['reason'] ?? null,
            ]);
        })->values();

        $hasMore = $user->notifications()
            ->where('created_at', '<', $windowStart)
            ->exists();

        return response()->json([
            'items'    => $items,
            'has_more' => $hasMore,
        ]);
    }

    public function markRead(Request $request, string $id)
    {
        $notification = $request->user()->notifications()->findOrFail($id);
        $notification->markAsRead();

        return response()->json(['ok' => true]);
    }

    public function markAllRead(Request $request)
    {
        $user = $request->user();
        $excluded = array_merge(self::SERVICE_TYPES, self::ORDER_TYPES);
        $placeholders = implode(',', array_fill(0, count($excluded), '?'));
        $user->unreadNotifications()
            ->whereRaw("(data::jsonb->>'type') NOT IN ($placeholders)", $excluded)
            ->get()
            ->each->markAsRead();

        return response()->json(['ok' => true]);
    }

    public function orders(Request $request)
    {
        $user = $request->user();
        [$before, $windowStart] = $this->window($request);

        $placeholders = implode(',', array_fill(0, count(self::ORDER_TYPES), '?'));

        $query = $user->notifications()
            ->whereRaw("(data::jsonb->>'type') IN ($placeholders)", self::ORDER_TYPES);

        $items = (clone $query)
            ->where('created_at', '>=', $windowStart)
            ->when($before, fn($q) => $q->where('created_at', '<', $before))
            ->latest()
            ->get()
            ->map(fn($n) => [
                'id'         => $n->id,
                'type'       => $n->data['type'],
                'order_id'   => $n->data['order_id'] ?? null,
                'read_at'    => $n->read_at?->toIso8601String(),
                'created_at' => $n->created_at->toIso8601String(),
                'data'       => $n->data,
            ])->values();

        $hasMore = (clone $query)->where('created_at', '<', $windowStart)->exists();

        $unreadCount = $user->unreadNotifications()
            ->whereRaw("(data::jsonb->>'type') IN ($placeholders)", self::ORDER_TYPES)
            ->count();

        return response()->json([
            'items'        => $items,
            'unread_count' => $unreadCount,
            'has_more'     => $hasMore,
        ]);
    }

    public function markAllOrdersRead(Request $request)
    {
        $user = $request->user();
        $placeholders = implode(',', array_fill(0, count(self::ORDER_TYPES), '?'));
        $user->unreadNotifications()
            ->whereRaw("(data::jsonb->>'type') IN ($placeholders)", self::ORDER_TYPES)
            ->get()
            ->each->markAsRead();

        return response()->json(['ok' => true]);
    }

    public function markBroadcastRead(Request $request, int $id)
    {
        // Stub kept for backward compatibility — old broadcasts no longer exist
        return response()->json(['ok' => true]);
    }

    public function markAllServiceRead(Request $request)
    {
        $user = $request->user();

        $placeholders = implode(',', array_fill(0, count(self::SERVICE_TYPES), '?'));
        $user->unreadNotifications()
            ->whereRaw("(data::jsonb->>'type') IN ($placeholders)", self::SERVICE_TYPES)
            ->get()
            ->each->markAsRead();

        return response()->json(['ok' => true]);
    }

    // Keep old messages methods for backwards compat (used by admin MessageController tests etc.)
    public function messages(Request $request)
    {
        return $this->service($request);
    }
}
