<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class NotificationController extends Controller
{
    // Notification types generated by the platform (go to "Сервис" tab)
    private const SERVICE_TYPES = ['idol_approved', 'idol_rejected', 'admin_broadcast', 'low_rating_warning', 'admin_rating'];
    private const ORDER_TYPES   = ['order_created', 'order_accepted', 'order_cancelled'];

    public function index(Request $request)
    {
        $user = $request->user();

        $excluded = array_merge(self::SERVICE_TYPES, self::ORDER_TYPES);
        $notifications = $user->notifications()
            ->latest()
            ->take(30)
            ->get()
            ->filter(fn($n) => !in_array($n->data['type'] ?? '', $excluded))
            ->values()
            ->map(fn($n) => [
                'id' => $n->id,
                'source' => 'notification',
                'type' => $n->data['type'] ?? 'info',
                'message' => $n->data['message'] ?? '',
                'reason' => $n->data['reason'] ?? null,
                'read_at' => $n->read_at?->toIso8601String(),
                'created_at' => $n->created_at->toIso8601String(),
            ]);

        $placeholders = implode(',', array_fill(0, count($excluded), '?'));
        $unread = $user->unreadNotifications()
            ->whereRaw("(data::jsonb->>'type') NOT IN ($placeholders)", $excluded)
            ->count();

        return response()->json([
            'notifications' => $notifications,
            'unread_count' => $unread,
        ]);
    }

    public function service(Request $request)
    {
        $user = $request->user();

        $placeholders = implode(',', array_fill(0, count(self::SERVICE_TYPES), '?'));
        $items = $user->notifications()
            ->whereRaw("(data::jsonb->>'type') IN ($placeholders)", self::SERVICE_TYPES)
            ->latest()
            ->take(30)
            ->get()
            ->map(fn($n) => [
                'id'         => $n->id,
                'source'     => 'notification',
                'type'       => $n->data['type'] ?? null,
                'title'      => $n->data['title'] ?? null,
                'message'    => $n->data['message'] ?? '',
                'reason'     => $n->data['reason'] ?? null,
                'read_at'    => $n->read_at?->toIso8601String(),
                'created_at' => $n->created_at->toIso8601String(),
            ]);

        $unreadCount = $user->unreadNotifications()
            ->whereRaw("(data::jsonb->>'type') IN ($placeholders)", self::SERVICE_TYPES)
            ->count();

        return response()->json([
            'items'        => $items,
            'unread_count' => $unreadCount,
        ]);
    }

    public function markRead(Request $request, string $id)
    {
        $notification = $request->user()->notifications()->findOrFail($id);
        $notification->markAsRead();

        return response()->json(['ok' => true]);
    }

    public function markAllRead(Request $request)
    {
        $user = $request->user();
        $excluded = array_merge(self::SERVICE_TYPES, self::ORDER_TYPES);
        $placeholders = implode(',', array_fill(0, count($excluded), '?'));
        $user->unreadNotifications()
            ->whereRaw("(data::jsonb->>'type') NOT IN ($placeholders)", $excluded)
            ->get()
            ->each->markAsRead();

        return response()->json(['ok' => true]);
    }

    public function orders(Request $request)
    {
        $user = $request->user();

        $placeholders = implode(',', array_fill(0, count(self::ORDER_TYPES), '?'));
        $items = $user->notifications()
            ->whereRaw("(data::jsonb->>'type') IN ($placeholders)", self::ORDER_TYPES)
            ->latest()
            ->take(30)
            ->get()
            ->map(fn($n) => [
                'id'         => $n->id,
                'type'       => $n->data['type'],
                'order_id'   => $n->data['order_id'] ?? null,
                'read_at'    => $n->read_at?->toIso8601String(),
                'created_at' => $n->created_at->toIso8601String(),
                'data'       => $n->data,
            ]);

        $unreadCount = $user->unreadNotifications()
            ->whereRaw("(data::jsonb->>'type') IN ($placeholders)", self::ORDER_TYPES)
            ->count();

        return response()->json([
            'items'        => $items,
            'unread_count' => $unreadCount,
        ]);
    }

    public function markAllOrdersRead(Request $request)
    {
        $user = $request->user();
        $placeholders = implode(',', array_fill(0, count(self::ORDER_TYPES), '?'));
        $user->unreadNotifications()
            ->whereRaw("(data::jsonb->>'type') IN ($placeholders)", self::ORDER_TYPES)
            ->get()
            ->each->markAsRead();

        return response()->json(['ok' => true]);
    }

    public function markBroadcastRead(Request $request, int $id)
    {
        // Stub kept for backward compatibility — old broadcasts no longer exist
        return response()->json(['ok' => true]);
    }

    public function markAllServiceRead(Request $request)
    {
        $user = $request->user();

        $placeholders = implode(',', array_fill(0, count(self::SERVICE_TYPES), '?'));
        $user->unreadNotifications()
            ->whereRaw("(data::jsonb->>'type') IN ($placeholders)", self::SERVICE_TYPES)
            ->get()
            ->each->markAsRead();

        return response()->json(['ok' => true]);
    }

    // Keep old messages methods for backwards compat (used by admin MessageController tests etc.)
    public function messages(Request $request)
    {
        return $this->service($request);
    }
}
